language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - php artisan key:generate
  - composer self-update
  - composer install --no-interaction
